### ISSUE TITLE
How to point wheel items towards wheel center (item direction towards wheel center) ?

### ISSUE THREAD

**Issue by shaileshBhokare** [DenisBogatirov/circle_wheel_scroll#13]
I'm practising about this library and I'm trying to direct my wheel items towards wheel centre. Thank you :-)

**Comment by Zamorite** [comment]
Looks like if you use `Axis.horizontal`, each child in `CircleListScrollView` spans full width. It prefers to align the item towards the left of the full width.

Try wrapping your child in a `Center` widget, as shown in the example code and they should be centered nicely.
