### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by a6a18** [DenisBogatirov/circle_wheel_scroll#16]
Will this package support for null safety?

**Comment by mrripp3r** [comment]
I have the same concern. I have a project that uses this package and it's stuck!! We need it to support null safety

**Comment by mrripp3r** [comment]
Any update on null safety?

**Comment by Nabin0433** [comment]
same

**Comment by andythedishwasher** [comment]
I'm currently working on a solution via the dart migration tool, so if I succeed I will send a pull request. I both want to use this widget and want the job skill of learning to migrate outdated flutter packages.

**Comment by mohamoha6200** [comment]
Any luck guys ?
